### ISSUE TITLE
[Suggestion] Controller / Templates / JS integration?

### ISSUE THREAD

**Issue by Spomky** [web-auth/webauthn-framework#116]
I am wondering if it is relevant to integrate the controller [showed in the documentation](https://webauthn-doc.spomky-labs.com/deep-into-the-framework/register-authenticators#the-symfony-way) directly in the symfony bundle.

We could imagine new configuration options to enable that feature. The options will be very similar to the ones for the firewall.
With this feature, developers will have nearly nothing to do but the repositories, the configuration and the templates (by the way basic templates/js could be also provied by the bundle).

```yaml
webauthn:
    controller: # Name to be confirmed
        enabled: true
        options_path: '/add/device/options'
        result_path: '/add/device'
        profile: 'default'
        options_storage: 'App\Handler\MyCustomRequestOptionsStorage'
        options_handler: 'App\Handler\MyCustomRequestOptionsHandler'
        success_handler: 'App\Handler\MyCustomAuthenticationSuccessHandler'
        failure_handler: 'App\Handler\MyCustomAuthenticationFailureHandler'
```

Any thoughts?
