### ISSUE TITLE
Wrong symfony service definition for Webauthn\AuthenticatorAttestationResponseValidator class

### ISSUE THREAD

**Issue by jmalinens** [web-auth/webauthn-framework#169]
**Describe the bug**
Looks like there is wrong service definition which breaks Symfony 4.4 integration

https://github.com/web-auth/webauthn-framework/blob/v3.3/src/symfony/src/Resources/config/services.php#L44
https://github.com/web-auth/webauthn-framework/blob/v3.3/src/webauthn/src/AuthenticatorAttestationResponseValidator.php#L79

Error:
```
The service "Webauthn\AuthenticatorAttestationResponseValidator" has a dependency on a non-existent service "@monolog.logger".
```

**Comment by Spomky** [comment]
Hi @jmalinens,

Thank you for reporting this issue.
The service definition looks good. No logging service is set here, only the required arguments.
A logger is set by calling `setLogger` using a [dedicated compiler pass](https://github.com/web-auth/webauthn-framework/blob/v3.3/src/symfony/src/DependencyInjection/Compiler/LoggerSetterCompilerPass.php).
In addition, the service that is passed is named `webauthn.logger` which is an alias of the configuration of the same name.

Can you share here the configuration of the bundle (especially the option `webauthn:logger: '...'`)?

**Comment by jmalinens** [comment]
```
webauthn:
    credential_repository: 'Webauthn\Bundle\Repository\PublicKeyCredentialSourceRepository'
    user_repository: 'App\Repository\PublicKeyCredentialUserEntityRepository'
    logger: '@monolog.logger'
    creation_profiles:
        default:
            rp:
                name: '%webauthn.relaying_party_name%'
                id: '%webauthn.relaying_party_id%'
            authenticator_selection_criteria:
                attachment_mode: !php/const Webauthn\AuthenticatorSelectionCriteria::AUTHENTICATOR_ATTACHMENT_PLATFORM
                require_resident_key: false
                user_verification: !php/const Webauthn\AuthenticatorSelectionCriteria::USER_VERIFICATION_REQUIREMENT_DISCOURAGED
#            attestation_conveyance: !php/const Webauthn\PublicKeyCredentialCreationOptions::ATTESTATION_CONVEYANCE_PREFERENCE_DIRECT

    request_profiles:
        default:
            rp_id: '%webauthn.relaying_party_id%'
            user_verification: 'discouraged' #'required'
```
