### ISSUE TITLE
The service "App\Repository\PublicKeyCredentialUserEntityRepository" must implement ObjectRepository (or extend a base class, like ServiceEntityRepository).

### ISSUE THREAD

**Issue by hiniestic** [web-auth/webauthn-framework#225]
I'm trying to run a project just with this bundle but with autowire: false.
I have set up webauthn.yml as:

```
webauthn:
    credential_repository: 'test.repository.public_key_credential_source_repository'
    user_repository: 'test.repository.public_key_credential_user_entity_repository'

```

and my service.yml is:

```
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'


    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
        

    App\Repository\PublicKeyCredentialUserEntityRepository:
        class: App\Repository\PublicKeyCredentialUserEntityRepository
        autowire: true
        tags: ['doctrine.repository_service']
    #    arguments: ['@Doctrine\Persistence\ManagerRegistry']
    App\Repository\PublicKeyCredentialSourceRepository:
        class: App\Repository\PublicKeyCredentialSourceRepository
        autowire: true
        tags: ['doctrine.repository_service']

    # Webauth
#-------------------------------------#

    # ------------------------------------------------------------------------------------------------------------------
    #
    # Repositories
    #
    # ------------------------------------------------------------------------------------------------------------------

    test.repository.public_key_credential_user_entity_repository:
        class:     App\Repository\PublicKeyCredentialUserEntityRepository
        tags: ['doctrine.repository_service']
        factory:   ["@doctrine.orm.entity_manager", getRepository]
        arguments: ['App\Entity\User']

    test.security.webauth.user_provider:
        class: App\Security\UserProvider
        arguments: ["@test.repository.public_key_credential_user_entity_repository", "@session", "@doctrine.orm.entity_manager", "@event_dispatcher", "@request_stack"]

    test.repository.public_key_credential_source_repository:
        class:     App\Repository\PublicKeyCredentialSourceRepository
        factory:   ["@doctrine.orm.entity_manager", getRepository]
        arguments: [App\Entity\PublicKeyCredentialSource]

```

But I get the issue The service "App\Repository\PublicKeyCredentialSourceRepository" must implement ObjectRepository (or extend a base class, like ServiceEntityRepository).

I have try the bundle in a new project with autowire: true and works ok, but can't find the issue with the PublicKeyCredentialSourceRepository when autowire is turn off.
