### ISSUE TITLE
How to enroll an existing user? 

### ISSUE THREAD

**Issue by janklan** [web-auth/webauthn-framework#336]
### Description

I'm wondering how to allow existing users (say provisioned via SAML, or any other way) use webauthn as an alternative way to authenticate (alongside of their existing username&password)

I'm playing around with your Symfony bundle and the Stimulus controller. I managed to get it working to the point when the browser is asking me for the token, and then attempts to authenticate. Authentication fails because the token is not registered. When I log in to my app and try to "register" the token (assign it to the current user, really), I get "User already exists" error, which is correct.

Is there a way to skip creating the user and jump straight to storing the public key etc?

**Comment by janklan** [comment]
Actually, this opens another related question: currently the Stimulus controller requires the username to be provided by the web browser. I noticed `Webauthn\Bundle\DependencyInjection\Factory\Security\WebauthnFactory` provides dynamic routes that handle the communication for each firewall, but I didn't find an obvious way for me to implement those routes myself - or at least the "register options"path.

My overarching goal here is to provide the user details on the server side, otherwise any authenticated user would be allowed to enrol a token under an email the user doesn't own.

I could autowire the the token into the repositories that fetch user information from the database and compare whether the ID belongs to the current user, but that's a bit clunky.

**Comment by Spomky** [comment]
Hi,

This is my mistake: the documentation is not up to date about the Stimulus Actions.

1. Create additional routes.
This step is done by simple configuration keys like [in the demo](https://github.com/web-auth/symfony-demo/blob/production/config/packages/webauthn.yaml#L33-L39) and [explained in the documentation](https://webauthn-doc.spomky-labs.com/symfony-bundle/advanced-behaviors/register-authenticators).
In your case, the user self-enroll authenticators:
```yaml
webauthn:
    controllers:
        enabled: true
        creation:
            from_user_account: #Unique name
                options_path: '/profile/security/devices/add/options' # To be modified
                result_path: '/profile/security/devices/add' # To be modified
                user_entity_guesser: Webauthn\Bundle\Security\Guesser\CurrentUserEntityGuesser
```

Do not forget to protect those routes:
```yaml
security:
    access_control:
        - { path: ^/profile,  roles: IS_AUTHENTICATED_FULLY }
```

2. Use the Stimulus Actions with these new routes
As showed [in the demo](https://github.com/web-auth/symfony-demo/blob/production/templates/authenticators/index.html.twig#L40-L52), you can customize the routes. Here we use the ones created by the above configuration.
Routes are:
* `creationOptionsUrl`: webauthn.controller.creation.request.**from_user_account** (**from_user_account** is the unique name from the configuration
* `creationResultUrl`: webauthn.controller.creation.response.**from_user_account**

No username or display name is needed here as the user entity is *guessed* depending on the `user_entity_guesser`.
The User Entity Guesser is a service that can retrieve the user from the request.
It could be
* the user itself (the use case above),
* an admin interacting for a user (e.g. IT staff enrolling new employees),
* an anonymous user with a unique token in case of loss of account access (typically sent be email like when password is lost)
* ...
