### ISSUE TITLE
Login dosent work after update to 4.5.0

### ISSUE THREAD

**Issue by tydoo** [web-auth/webauthn-framework#370]
### Version(s) affected

4.5.0

### Description

When i want to login with a Yubikey, i have this error from update to v4.5.0: 

`Unable to load the data`

Before, i'm on 4.0.5 version and all its works.

Registration token continue to work normaly.

I'm on symfony 6.2

Please help me.

Thanks

### How to reproduce

**POST data to login/option**
```
{
    "attestation": "direct",
    "authenticatorSelection": {
        "requireResidentKey": true,
        "userVerification": "required"
    }
}
```

**RESPONSE from login/option**
```
{
    "challenge":"j6ZGgl6E-7LjZIRLfikamec2QURvcmGVQmi_jOhZn5M",
    "rpId":"localhost",
    "userVerification":"required",
    "status":"ok",
    "errorMessage":""
}
```

POST data to login
```
{
    "id": "k_KW_ZtTZ1b_BQiB408aWn2_TqAvq8lA3SE4UG6tLcDHiormucOVc-jwFbd535tV",
    "type": "public-key",
    "rawId": "k\/KW\/ZtTZ1b\/BQiB408aWn2\/TqAvq8lA3SE4UG6tLcDHiormucOVc+jwFbd535tV",
    "response": {
        "clientDataJSON": "eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoiajZaR2dsNkUtN0xqWklSTGZpa2FtZWMyUVVSdmNtR1ZRbWlfak9oWm41TSIsIm9yaWdpbiI6Imh0dHBzOi8vbG9jYWxob3N0OjgwMDAiLCJjcm9zc09yaWdpbiI6ZmFsc2V9",
        "authenticatorData": "SZYN5YgOjGh0NBcPZHZgW4\/krrmihjLHmVzzuoMdl2MFAAAABA==",
        "signature": "MEUCIAKL1cDCYuozb0ySljtKA7RFd9i8pBDHQpfOjB\/y7iC4AiEAyJNhyOPKoDsF6ylxb+l8rN4sb+e9GBzBbtVWQVtYOIE=",
        "userHandle": "dGJveWVyQGVjb3dhbi5mcg=="
    }
}
```

RESPONSE from login
```
{
    "status":
    "error",
    "errorMessage":"Unable to load the data"
}
```

My config file : 

```
webauthn:
    credential_repository: 'App\Repository\PublicKeyCredentialSourceRepository'
    user_repository: 'App\Repository\PublicKeyCredentialUserEntityRepository'
    creation_profiles:
        default:
            rp:
                name: '%env(RELAYING_PARTY_NAME)%'
                id: '%env(RELAYING_PARTY_ID)%'
            authenticator_selection_criteria:
                require_resident_key: true
                user_verification: !php/const Webauthn\AuthenticatorSelectionCriteria::USER_VERIFICATION_REQUIREMENT_REQUIRED
            attestation_conveyance: !php/const Webauthn\PublicKeyCredentialCreationOptions::ATTESTATION_CONVEYANCE_PREFERENCE_DIRECT
    request_profiles:
        default:
            rp_id: '%env(RELAYING_PARTY_ID)%'
            user_verification: !php/const Webauthn\AuthenticatorSelectionCriteria::USER_VERIFICATION_REQUIREMENT_REQUIRED
    controllers:
        enabled: true
        creation:
            additional_authenticator:
                options_path: '/account/security/webauthn/add/options'
                result_path: '/account/security/webauthn/add'
                user_entity_guesser: 'Webauthn\Bundle\Security\Guesser\CurrentUserEntityGuesser'
    metadata:
        enabled: true
        mds_repository: App\Repository\MetadataStatementRepository
        status_report_repository: App\Repository\StatusReportRepository
```
