### ISSUE TITLE
options_path on controllers UX dosent works

### ISSUE THREAD

**Issue by tydoo** [web-auth/webauthn-framework#713]
### Version(s) affected

5.2

### Description

When i try to login with Symfony UX, Symofny send Ajax request to ``/request/options`` and not to ``/login/webauthn/options``

### How to reproduce

All config is from docs 5.2

config/packages/webauthn.yaml
```
# Please see the following page for more information: https://webauthn-doc.spomky-labs.com/the-webauthn-server/the-symfony-way#configuration

webauthn:
    controllers:
        enabled: true
        request:
            login:
                options_path: '/login/webauthn/options'
    credential_repository: 'Webauthn\Bundle\Repository\DummyPublicKeyCredentialSourceRepository' # CREATE YOUR REPOSITORY AND CHANGE THIS!
    user_repository: 'Webauthn\Bundle\Repository\DummyPublicKeyCredentialUserEntityRepository' # CREATE YOUR REPOSITORY AND CHANGE THIS!
    creation_profiles:
        default:
            rp:
                name: '%env(RELYING_PARTY_NAME)%' # Please adapt the env file with the correct relaying party ID or set null
                id: '%env(RELYING_PARTY_ID)%' # Please adapt the env file with the correct relaying party ID or set null
    request_profiles:
        default:
            rp_id: '%env(RELYING_PARTY_ID)%' # Please adapt the env file with the correct relaying party ID or set null
```

form login
```
<form action="{{ path('security.login') }}" method="post" {{ stimulus_controller('@web-auth/webauthn-stimulus', { useBrowserAutofill: true, requestResultUrl: path('webauthn.controller.request.request.login'), requestResultField: 'input[name="_assertion"]', } ) }}>
		<label for="username">Usenrame:</label>
		<input type="text" id="username" name="_username" value="{{ last_username }}" placeholder="Type your username here" autocomplete="username webauthn">
		<input type="hidden" id="assertion" name="_assertion">
		<button id="login" name="login" type="submit">login</button>
	</form>
```
