### ISSUE TITLE
authenticator selection criteria of profile for creation is not working

### ISSUE THREAD

**Issue by tydoo** [web-auth/webauthn-framework#715]
### Version(s) affected

5.2

### Description

All options is not working

### How to reproduce

webauthn.yaml
```yaml
# Please see the following page for more information: https://webauthn-doc.spomky-labs.com/the-webauthn-server/the-symfony-way#configuration

webauthn:
    credential_repository: 'App\Repository\WebauthnCredentialRepository'
    user_repository: 'App\Repository\WebauthnUserEntityRepository'
    creation_profiles:
        test5:
            default:
                name: '%env(RELYING_PARTY_NAME)%' # Please adapt the env file with the correct relaying party ID or set null
                id: '%env(RELYING_PARTY_ID)%' # Please adapt the env file with the correct relaying party ID or set null
            authenticator_selection_criteria:
                require_resident_key: true
                user_verification: 'required'
    request_profiles:
        default:
            rp_id: '%env(RELYING_PARTY_ID)%' # Please adapt the env file with the correct relaying party ID or set null
            user_verification: 'required'
    controllers:
        enabled: true
        request:
            login:
                options_path: '/login/webauthn/options'
                result_path: '/login/webauthn/result'
        creation:
            from_user_account: # Endpoints accessible by the user itself
                options_path: '/account/security/devices/add/options' # Path to the creation options controller
                result_path: '/account/security/devices/add' # Path to the response controller
                user_entity_guesser: 'App\Guesser\FromQueryParameterGuesser'
                hide_existing_credentials: false

```

When i try /account/security/devices/add/options : 
```json
{
    "challenge": "HLEjca67bJEfnuas-m4SI0cdij_dROszNm_0NxnifzQ",
    "rp": {
        "id": "localhost",
        "name": "Lebackoffice"
    },
    "user": {
        "id": "NGM5NGFiYjMtZDAwZC00MjdjLTkxNzgtNGNiOGMzZGYzNjdi",
        "name": "tydoo",
        "displayName": "tydoo2"
    },
    "pubKeyCredParams": [],
    "authenticatorSelection": {
        "userVerification": "preferred"
    },
    "attestation": "none",
    "excludeCredentials": [],
    "status": "ok",
    "errorMessage": ""
}
```

**Comment by Spomky** [comment]
The controller configuration is missing the profile name

```yaml
webauthn:
    ...
    controllers:
        enabled: true
        ...
        creation:
            from_user_account:
                options_path: '/account/security/devices/add/options'
                result_path: '/account/security/devices/add'
                user_entity_guesser: 'App\Guesser\FromQueryParameterGuesser'
                hide_existing_credentials: false
                profile: test5 # <= this line
```
