### ISSUE TITLE
Attestation statement format "packed" is not supported.

### ISSUE THREAD

**Issue by tydoo** [web-auth/webauthn-framework#716]
### Version(s) affected

5.2

### Description

I try to add Yubikey

### How to reproduce

the "attestation_conveyance: 'direct'" option send this error.

Without this options, its works, but without transports information.

![Image](https://github.com/user-attachments/assets/1af20dcf-5e34-4c37-9adb-44e859882b75)

webauthn.yaml
```yaml
# Please see the following page for more information: https://webauthn-doc.spomky-labs.com/the-webauthn-server/the-symfony-way#configuration

webauthn:
    credential_repository: 'App\Repository\WebauthnCredentialRepository'
    user_repository: 'App\Repository\WebauthnUserEntityRepository'
    creation_profiles:
        default:
            rp:
                name: '%env(RELYING_PARTY_NAME)%' # Please adapt the env file with the correct relaying party ID or set null
                id: '%env(RELYING_PARTY_ID)%' # Please adapt the env file with the correct relaying party ID or set null
            authenticator_selection_criteria:
                require_resident_key: true
                user_verification: 'required'
            attestation_conveyance: 'direct'
    request_profiles:
        default:
            rp_id: '%env(RELYING_PARTY_ID)%' # Please adapt the env file with the correct relaying party ID or set null
            user_verification: 'required'
    controllers:
        enabled: true
        request:
            login:
                options_path: '/login/webauthn/options'
                result_path: '/login/webauthn/result'
        creation:
            from_user_account: # Endpoints accessible by the user itself
                options_path: '/account/security/devices/add/options' # Path to the creation options controller
                result_path: '/account/security/devices/add' # Path to the response controller
                user_entity_guesser: 'App\Guesser\FromQueryParameterGuesser'
                hide_existing_credentials: false

```

### Additional Context
Docs 5.2 : https://webauthn-doc.spomky-labs.com/v5.2/the-project/the-project
![Image](https://github.com/user-attachments/assets/ca133dca-6591-4a35-8e8d-f5bd12e0c575)

**Comment by Spomky** [comment]
Hi,

As mentioned in the documentation, when you want to use attestation other than `none`, it is mandatory to have a Metadata Statement Repository and the associated Status Report Repository (can be the same class with the appropriate interface.

* https://webauthn-doc.spomky-labs.com/v5.2/webauthn-in-a-nutshell/attestation-and-metadata-statement: *It is mandatory to get the statement from the manufacturer of your authenticators otherwise the Attestation Statement won't be verified and the Attestation Ceremony will fail.*
* https://webauthn-doc.spomky-labs.com/v5.2/symfony-bundle/advanced-behaviors/attestation-and-metadata-statement
* https://webauthn-doc.spomky-labs.com/v5.2/pure-php/advanced-behaviours/attestation-and-metadata-statement#metadata-statement-repository

```yaml
webauthn:
    metadata:
        enabled: true
        mds_repository: 'App\Repository\MdsRepository'
        status_report_repository: 'App\Repository\MdsRepository'
```
