### ISSUE TITLE
Support WebAuthn Conditional Create (ignore isUserPresent/isUserVerified flags)

### ISSUE THREAD

**Issue by joostdebruijn** [web-auth/webauthn-framework#719]
### Description

Currently, the library requires `isUserPresent` to be true during credential registration and assertion ceremonies and `isUserVerified` to be true when the options have `USER_VERIFICATION_REQUIREMENT_REQUIRED` set.

However, with Conditional Create, it is expected that both `isUserPresent` and `isUserVerified` may be **false** in the registration response. According to the Chrome and WebAuthn documentation, the server must ignore these flags when verifying credentials created via Conditional Create.

I can implement a custom `CeremonyStepManager` myself, but I would prefer to not do that and have the possibility to get one from the Factory configured for handling Conditional Create requests.

WebAuthn Conditional Create is described in the following resources:
- [WebAuthn Conditional Create Explainer](https://github.com/w3c/webauthn/wiki/Explainer:-Conditional-Create)
- [Chrome Platform Status](https://chromestatus.com/feature/5135710007590912)
- [Chrome Developer Docs](https://developer.chrome.com/docs/identity/webauthn-conditional-create)

**Comment by Spomky** [comment]
Hi @joostdebruijn,

It has took me some time to address this feature.
Please have a look at #748. I will be happy if you could test it and tell me if it is fine.
There is a new `conditionalCreateCeremony` method:

```php
# Using the library
use Webauthn\CeremonyStep\CeremonyStepManagerFactory;
use Webauthn\AuthenticatorAttestationResponseValidator;

// Create the factory
$factory = new CeremonyStepManagerFactory();
$factory->setAllowedOrigins(['https://example.com']);

// Use conditionalCreateCeremony() for auto-register
$ceremonyStepManager = $factory->conditionalCreateCeremony();

// Validate the response
$validator = new AuthenticatorAttestationResponseValidator(
    $ceremonyStepManager
);

$publicKeyCredentialSource = $validator->check(
    authenticatorAttestationResponse: $response,
    publicKeyCredentialCreationOptions: $options,
    host: 'example.com'
);
```

```yaml
# Using Symfony
webauthn:
    creation_profiles:
        # Standard registration profile
        auto_register:
            rp:
                id: 'example.com'
            conditional_create: true # Default is false

    controllers:
        enabled: true
        creation:
            auto_register:
                profile: 'auto_register'
                # ... other options
```

And using the new Stimulus Controller 

```html
<form
    id="auto-register-form"
    style="display: none;"
    data-controller="web-auth--registration"
    data-web-auth--registration-options-url-value="/webauthn/auto-register/options"
    data-web-auth--registration-result-url-value="/webauthn/auto-register/verify"
    data-web-auth--registration-auto-register-value="true"
    data-action="submit->web-auth--registration#register">
    <input type="hidden" name="username" value="john.doe">
</form>
```
